# Generated by Django 4.1.4 on 2022-12-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_rename_fname_stud_fullname_remove_stud_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='grade',
        ),
    ]
