# Generated by Django 4.1.4 on 2022-12-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='fName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='lName',
        ),
    ]
